<?php
/**
 * Implements hook_theme().
 */
function pablo_theme($existing, $type, $theme, $path) {
  return [
    'cats_template' => [
      'variables' => [
        'catsTitle' => NULL,
        'form' => NULL,
        'cats' => NULL,
        'DeleteForm' => NULL,
        'EditForm' => NULL,
      ],
    ],
    'cats-items' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'cats-list' => [
      'variables' => [
        'items' => NULL,
        'DeleteForm' => NULL,
        'EditForm' => NULL,
        'DeleteAllForm' => NULL,
        'DeleteMultipleForm' => NULL,
      ],
    ],
  ];
}
